name: build-open-window-build
on:
  push:
    tags:
        - "v*.*.*"
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GO_VERSION: 1.20.6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: actions/setup-go@v4
      with:
        go-version: $GO_VERSION
    - uses: golang/govulncheck-action@v1
      name: govulncheck
      with:
        go-version-input: $GO_VERSION
    - run: go version
      name: display go version
    - name: unit tests
      run: go test ./... -short -coverprofile=cov.out
    - name: build executable
      run: go build .
    - name: sonar
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
